# General site settings
title: blog.peddy.ai
email: peddy@peddy.ai
description:  
  math | music | machines
baseurl: "" # empty subpath 
url: "http://blog.peddy.ai" # the site base hostname & protocol
twitter_username: unclepeddy
github_username:  unclepeddy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-auto-image
  - jekyll-sitemap
permalink: pretty

# Custom collections settings
collections:
  tags:
    output: true
    permalink: /tags/:name
  thoughts:
    output: true
    permalink: /thoughts/:title
  media:
    output: true
    permalink: /media/:title

# Layout settings
defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "thought"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
